---
title: "pdc-jcomponent"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
polling = read.csv("Assam_custom_data.csv")
str(polling)
```



```{r}
summary(polling)
```
```{r}

#install.packages("mice")
library("mice")
simple=polling[c("TimesNowVMR","IndiaTodayAxis","CountDifference","propBJP")]
summary(simple)
```
```{r}
#Impute the table data using mice library to remove the NA values
set.seed(100)
imputed= complete(mice(simple))
summary(imputed)
sum(is.na(imputed))
```

```{r}
#Change the Polling Column values from Simple Column values (without NA values)
polling$TimesNowVMR=imputed$TimesNowVMR
polling$IndiaTodayAxis=imputed$IndiaTodayAxis
polling$CountDifference=imputed$CountDifference
polling$propBJP=imputed$propBJP
summary(polling)
sum(is.na(imputed))
```

##Creating the Baseline Model
```{r}
Train=subset(polling,Year==2011|Year==2016)
Test=subset(polling,Year==2021)
table(Train$BJP)
```


```{r}
table(sign(Train$TimesNowVMR))
```

```{r}
table(Train$BJP,sign(Train$TimesNowVMR))

```

## CREATING A LOGISTIC REGRESSION BASED MODEL
```{r}
cor(Train[c("TimesNowVMR","IndiaTodayAxis","CountDifference","propBJP","BJP")]) 
```

## glm used for logistic regression
```{r}
#Model 1 where result is predicted using the propBJP column
model1 <- function(){
mod1=glm(BJP~propBJP, data=Train,family="binomial")
pred1=predict(mod1,type="response")
table(Train$BJP,pred1>=0.5)
}

```

```{r}
#Model 2 where result is predicted using the TimesNowVMR and IndiaTodayAxis columns
model2 <- function(){
mod2=glm(BJP~TimesNowVMR+IndiaTodayAxis, data=Train,family="binomial")
pred1=predict(mod2,type="response")
table(Train$BJP,pred1>=0.5)
}

```


```{r}
#Model 3 where result is predicted using the TimesNowVMR and propBJP columns
model3 <- function(){
mod3=glm(BJP~TimesNowVMR+propBJP, data=Train,family="binomial")
pred1=predict(mod3,type="response")
table(Train$BJP,pred1>=0.5)
}

```


```{r}
#Model 4 where result is predicted using the IndiaTodayAxis and propBJP columns
model4 <- function(){
mod4=glm(BJP~IndiaTodayAxis+propBJP, data=Train,family="binomial")
pred1=predict(mod4,type="response")
table(Train$BJP,pred1>=0.5)
}

```



```{r}
#Parallellizing the training of the 4 LR models using foreach
library(doParallel)
library(foreach)
cl<-makeCluster(4)
registerDoParallel(cl)
mylist <- list (model1(),model2(),model3(),model4())
mylist<-foreach(i=1:4) %dopar% (mylist[[i]])
mylist
```
```{r}
test <- function(mod){
TestPrediction=predict(mod,newdata=Test,type="response")
table(Test$BJP, TestPrediction>=0.5)}
```

```{r}
#Parallellizing the testing of the 4 LR models using foreach
testlist <- list (mod1,mod2,mod3,mod4)
reslist<-foreach(i=1:4) %dopar% (test(testlist[[i]]))
reslist
```




```{r}
result <- function(mod){
summary(mod)
}
```


```{r}
#Parallellizing the summarised results of the 4 LR models using foreach
sumlist <- list (mod1,mod2,mod2,mod4)
reslist <- foreach(i=1:4) %dopar% (result(sumlist[[i]]))
reslist
```
